# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# This uses the packaged box from https://fedoraproject.org/cloud/download
# $ vagrant box add --name fedora/42-cloud-base \
#    https://download.fedoraproject.org/pub/fedora/linux/releases/42/Cloud/x86_64/images/Fedora-Cloud-Base-Vagrant-libvirt-42-1.1.x86_64.vagrant.libvirt.box

Vagrant.configure("2") do |config|
  config.vm.box = "fedora/42-cloud-base"
  config.vm.box_version = "0"
  config.vm.provider :libvirt do |libvirt|
    libvirt.machine_virtual_size = 10
  end
  config.vm.provision "shell", name: "Grow root filesystem", inline: <<-SHELL
    growpart /dev/vda 4
    btrfs filesystem resize max / 2> /dev/null
  SHELL
end
