Vagrant.configure("2") do |config|
  config.vm.box = "jborean93/WindowsServer2022"
  config.vm.provider :libvirt do |libvirt|
    (0..3).each do |i|
      libvirt.storage :file, :size => '2GB', name: "disk-#{i}"
    end
  end
end
