# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "fedora/40-cloud-base"
  config.vm.box_version = "40.20240414.0"
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end

end

